// Generated by CoffeeScript 1.4.0
(function() {
  var captions, color, dropPin, getPlacesNearby, latLng;

  latLng = function(location) {
    return new google.maps.LatLng(location.coords.latitude, location.coords.longitude);
  };

  getPlacesNearby = function(location) {
    var lat, lng, random;
    random = function() {
      return _.random(-100, 100) / 10000.0;
    };
    lat = location.coords.latitude;
    lng = location.coords.longitude;
    return _.map(_.range(80), function() {
      var newLocation;
      newLocation = _.clone(location);
      newLocation.coords = _.clone(location.coords);
      newLocation.coords.latitude = lat + random();
      newLocation.coords.longitude = lng + random();
      return newLocation;
    });
  };

  color = {
    green: '66CC33',
    red: 'FE7569'
  };

  captions = ['Great place to play backgammon!', 'Bananas...', 'Hidden shop'];

  dropPin = function(location, title, color, map) {
    var pinImage, pinShadow, positionMarker;
    pinImage = new google.maps.MarkerImage('http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|' + color, new google.maps.Size(21, 34), new google.maps.Point(0, 0), new google.maps.Point(10, 34));
    pinShadow = new google.maps.MarkerImage('http://chart.apis.google.com/chart?chst=d_map_pin_shadow', new google.maps.Size(40, 37), new google.maps.Point(0, 0), new google.maps.Point(12, 35));
    positionMarker = new google.maps.Marker({
      position: latLng(location),
      title: title,
      icon: pinImage,
      shadow: pinShadow
    });
    positionMarker.setMap(map);
    return google.maps.event.addListener(positionMarker, 'click', function() {
      var infowindow;
      infowindow = new google.maps.InfoWindow({
        content: "<b>" + title + "</b>"
      });
      return infowindow.open(map, positionMarker);
    });
  };

  google.maps.event.addDomListener(window, 'load', function() {
    return navigator.geolocation.getCurrentPosition(function(location) {
      var map;
      map = new google.maps.Map(document.getElementById("map_canvas"), {
        center: new google.maps.LatLng(location.coords.latitude, location.coords.longitude),
        zoom: 16,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });
      dropPin(location, 'You are here!', color.red, map);
      return _.each(getPlacesNearby(location), function(e) {
        return dropPin(e, captions[_.random(2)], color.green, map);
      });
    });
  });

  $(window).resize(function() {
    return $('#map_canvas').css('height', $(window).height() - 190);
  }).resize();

}).call(this);
